//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whip.XmlDataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Whip.XmlDataAccess.PropertyNames", typeof(PropertyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.
        /// </summary>
        internal static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        internal static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        internal static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artwork.
        /// </summary>
        internal static string Artwork {
            get {
                return ResourceManager.GetString("Artwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bandcamp.
        /// </summary>
        internal static string BandCamp {
            get {
                return ResourceManager.GetString("BandCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bands_in_town.
        /// </summary>
        internal static string BandsInTown {
            get {
                return ResourceManager.GetString("BandsInTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date_created.
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date_modified.
        /// </summary>
        internal static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disc.
        /// </summary>
        internal static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disc_count.
        /// </summary>
        internal static string DiscCount {
            get {
                return ResourceManager.GetString("DiscCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disc_no.
        /// </summary>
        internal static string DiscNo {
            get {
                return ResourceManager.GetString("DiscNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discs.
        /// </summary>
        internal static string Discs {
            get {
                return ResourceManager.GetString("Discs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        internal static string EventArtistList {
            get {
                return ResourceManager.GetString("EventArtistList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        internal static string EventCity {
            get {
                return ResourceManager.GetString("EventCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        internal static string EventCountry {
            get {
                return ResourceManager.GetString("EventCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        internal static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated.
        /// </summary>
        internal static string EventsUpdated {
            get {
                return ResourceManager.GetString("EventsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to venue.
        /// </summary>
        internal static string EventVenue {
            get {
                return ResourceManager.GetString("EventVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebook.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string FalseValue {
            get {
                return ResourceManager.GetString("FalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full_filepath.
        /// </summary>
        internal static string FullFilepath {
            get {
                return ResourceManager.GetString("FullFilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genre.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grouping.
        /// </summary>
        internal static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_fm.
        /// </summary>
        internal static string LastFm {
            get {
                return ResourceManager.GetString("LastFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_updated.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lyrics.
        /// </summary>
        internal static string Lyrics {
            get {
                return ResourceManager.GetString("Lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist.
        /// </summary>
        internal static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album_criteria.
        /// </summary>
        internal static string PlaylistAlbumCriteria {
            get {
                return ResourceManager.GetString("PlaylistAlbumCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist_criteria.
        /// </summary>
        internal static string PlaylistArtistCriteria {
            get {
                return ResourceManager.GetString("PlaylistArtistCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criteria.
        /// </summary>
        internal static string PlaylistCriteria {
            get {
                return ResourceManager.GetString("PlaylistCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criteria_group.
        /// </summary>
        internal static string PlaylistCriteriaGroup {
            get {
                return ResourceManager.GetString("PlaylistCriteriaGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criteria_groups.
        /// </summary>
        internal static string PlaylistCriteriaGroups {
            get {
                return ResourceManager.GetString("PlaylistCriteriaGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property_name.
        /// </summary>
        internal static string PlaylistCriteriaPropertyName {
            get {
                return ResourceManager.GetString("PlaylistCriteriaPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criteria_type.
        /// </summary>
        internal static string PlaylistCriteriaType {
            get {
                return ResourceManager.GetString("PlaylistCriteriaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string PlaylistCriteriaValue {
            get {
                return ResourceManager.GetString("PlaylistCriteriaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disc_criteria.
        /// </summary>
        internal static string PlaylistDiscCriteria {
            get {
                return ResourceManager.GetString("PlaylistDiscCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string PlaylistId {
            get {
                return ResourceManager.GetString("PlaylistId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max_tracks.
        /// </summary>
        internal static string PlaylistMaxTracks {
            get {
                return ResourceManager.GetString("PlaylistMaxTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order_by.
        /// </summary>
        internal static string PlaylistOrderBy {
            get {
                return ResourceManager.GetString("PlaylistOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order_by_descending.
        /// </summary>
        internal static string PlaylistOrderByDescending {
            get {
                return ResourceManager.GetString("PlaylistOrderByDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criteria_playlists.
        /// </summary>
        internal static string PlaylistsCriteria {
            get {
                return ResourceManager.GetString("PlaylistsCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ordered_playlists.
        /// </summary>
        internal static string PlaylistsOrdered {
            get {
                return ResourceManager.GetString("PlaylistsOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlists.
        /// </summary>
        internal static string PlaylistsRoot {
            get {
                return ResourceManager.GetString("PlaylistsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string PlaylistTitle {
            get {
                return ResourceManager.GetString("PlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        internal static string PlaylistTrack {
            get {
                return ResourceManager.GetString("PlaylistTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track_criteria.
        /// </summary>
        internal static string PlaylistTrackCriteria {
            get {
                return ResourceManager.GetString("PlaylistTrackCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filepath.
        /// </summary>
        internal static string PlaylistTrackFilepath {
            get {
                return ResourceManager.GetString("PlaylistTrackFilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks.
        /// </summary>
        internal static string PlaylistTracks {
            get {
                return ResourceManager.GetString("PlaylistTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relative_filepath.
        /// </summary>
        internal static string RelativeFilepath {
            get {
                return ResourceManager.GetString("RelativeFilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to release_type.
        /// </summary>
        internal static string ReleaseType {
            get {
                return ResourceManager.GetString("ReleaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to library.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color.
        /// </summary>
        internal static string RssColor {
            get {
                return ResourceManager.GetString("RssColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feed.
        /// </summary>
        internal static string RssFeed {
            get {
                return ResourceManager.GetString("RssFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feeds.
        /// </summary>
        internal static string RssFeeds {
            get {
                return ResourceManager.GetString("RssFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feed_url.
        /// </summary>
        internal static string RssFeedUrl {
            get {
                return ResourceManager.GetString("RssFeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon.
        /// </summary>
        internal static string RssIconUrl {
            get {
                return ResourceManager.GetString("RssIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rss.
        /// </summary>
        internal static string RssRoot {
            get {
                return ResourceManager.GetString("RssRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string RssTitle {
            get {
                return ResourceManager.GetString("RssTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        internal static string RssUrl {
            get {
                return ResourceManager.GetString("RssUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track_count.
        /// </summary>
        internal static string TrackCount {
            get {
                return ResourceManager.GetString("TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track_no.
        /// </summary>
        internal static string TrackNo {
            get {
                return ResourceManager.GetString("TrackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks.
        /// </summary>
        internal static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track_year.
        /// </summary>
        internal static string TrackYear {
            get {
                return ResourceManager.GetString("TrackYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string TrueValue {
            get {
                return ResourceManager.GetString("TrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wikipedia.
        /// </summary>
        internal static string Wikipedia {
            get {
                return ResourceManager.GetString("Wikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube.
        /// </summary>
        internal static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
    }
}
