//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whip.XmlDataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Whip.XmlDataAccess.PropertyNames", typeof(PropertyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        public static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artwork.
        /// </summary>
        public static string Artwork {
            get {
                return ResourceManager.GetString("Artwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bandcamp.
        /// </summary>
        public static string BandCamp {
            get {
                return ResourceManager.GetString("BandCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bands_in_town.
        /// </summary>
        public static string BandsInTown {
            get {
                return ResourceManager.GetString("BandsInTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date_created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date_modified.
        /// </summary>
        public static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disc.
        /// </summary>
        public static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disc_count.
        /// </summary>
        public static string DiscCount {
            get {
                return ResourceManager.GetString("DiscCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disc_no.
        /// </summary>
        public static string DiscNo {
            get {
                return ResourceManager.GetString("DiscNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discs.
        /// </summary>
        public static string Discs {
            get {
                return ResourceManager.GetString("Discs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        public static string EventArtistList {
            get {
                return ResourceManager.GetString("EventArtistList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        public static string EventCity {
            get {
                return ResourceManager.GetString("EventCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        public static string EventCountry {
            get {
                return ResourceManager.GetString("EventCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated.
        /// </summary>
        public static string EventsUpdated {
            get {
                return ResourceManager.GetString("EventsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to venue.
        /// </summary>
        public static string EventVenue {
            get {
                return ResourceManager.GetString("EventVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string FalseValue {
            get {
                return ResourceManager.GetString("FalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full_filepath.
        /// </summary>
        public static string FullFilepath {
            get {
                return ResourceManager.GetString("FullFilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grouping.
        /// </summary>
        public static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_fm.
        /// </summary>
        public static string LastFm {
            get {
                return ResourceManager.GetString("LastFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_updated.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lyrics.
        /// </summary>
        public static string Lyrics {
            get {
                return ResourceManager.GetString("Lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album_criteria.
        /// </summary>
        public static string PlaylistAlbumCriteria {
            get {
                return ResourceManager.GetString("PlaylistAlbumCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist_criteria.
        /// </summary>
        public static string PlaylistArtistCriteria {
            get {
                return ResourceManager.GetString("PlaylistArtistCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criteria.
        /// </summary>
        public static string PlaylistCriteria {
            get {
                return ResourceManager.GetString("PlaylistCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criteria_group.
        /// </summary>
        public static string PlaylistCriteriaGroup {
            get {
                return ResourceManager.GetString("PlaylistCriteriaGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criteria_groups.
        /// </summary>
        public static string PlaylistCriteriaGroups {
            get {
                return ResourceManager.GetString("PlaylistCriteriaGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property_name.
        /// </summary>
        public static string PlaylistCriteriaPropertyName {
            get {
                return ResourceManager.GetString("PlaylistCriteriaPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criteria_type.
        /// </summary>
        public static string PlaylistCriteriaType {
            get {
                return ResourceManager.GetString("PlaylistCriteriaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        public static string PlaylistCriteriaValue {
            get {
                return ResourceManager.GetString("PlaylistCriteriaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disc_criteria.
        /// </summary>
        public static string PlaylistDiscCriteria {
            get {
                return ResourceManager.GetString("PlaylistDiscCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string PlaylistId {
            get {
                return ResourceManager.GetString("PlaylistId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max_tracks.
        /// </summary>
        public static string PlaylistMaxTracks {
            get {
                return ResourceManager.GetString("PlaylistMaxTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order_by.
        /// </summary>
        public static string PlaylistOrderBy {
            get {
                return ResourceManager.GetString("PlaylistOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order_by_descending.
        /// </summary>
        public static string PlaylistOrderByDescending {
            get {
                return ResourceManager.GetString("PlaylistOrderByDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criteria_playlists.
        /// </summary>
        public static string PlaylistsCriteria {
            get {
                return ResourceManager.GetString("PlaylistsCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ordered_playlists.
        /// </summary>
        public static string PlaylistsOrdered {
            get {
                return ResourceManager.GetString("PlaylistsOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlists.
        /// </summary>
        public static string PlaylistsRoot {
            get {
                return ResourceManager.GetString("PlaylistsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string PlaylistTitle {
            get {
                return ResourceManager.GetString("PlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        public static string PlaylistTrack {
            get {
                return ResourceManager.GetString("PlaylistTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track_criteria.
        /// </summary>
        public static string PlaylistTrackCriteria {
            get {
                return ResourceManager.GetString("PlaylistTrackCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filepath.
        /// </summary>
        public static string PlaylistTrackFilepath {
            get {
                return ResourceManager.GetString("PlaylistTrackFilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks.
        /// </summary>
        public static string PlaylistTracks {
            get {
                return ResourceManager.GetString("PlaylistTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relative_filepath.
        /// </summary>
        public static string RelativeFilepath {
            get {
                return ResourceManager.GetString("RelativeFilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to release_type.
        /// </summary>
        public static string ReleaseType {
            get {
                return ResourceManager.GetString("ReleaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to library.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color.
        /// </summary>
        public static string RssColor {
            get {
                return ResourceManager.GetString("RssColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feed.
        /// </summary>
        public static string RssFeed {
            get {
                return ResourceManager.GetString("RssFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feeds.
        /// </summary>
        public static string RssFeeds {
            get {
                return ResourceManager.GetString("RssFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feed_url.
        /// </summary>
        public static string RssFeedUrl {
            get {
                return ResourceManager.GetString("RssFeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon.
        /// </summary>
        public static string RssIconUrl {
            get {
                return ResourceManager.GetString("RssIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rss.
        /// </summary>
        public static string RssRoot {
            get {
                return ResourceManager.GetString("RssRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string RssTitle {
            get {
                return ResourceManager.GetString("RssTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        public static string RssUrl {
            get {
                return ResourceManager.GetString("RssUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track_count.
        /// </summary>
        public static string TrackCount {
            get {
                return ResourceManager.GetString("TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track_no.
        /// </summary>
        public static string TrackNo {
            get {
                return ResourceManager.GetString("TrackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks.
        /// </summary>
        public static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track_year.
        /// </summary>
        public static string TrackYear {
            get {
                return ResourceManager.GetString("TrackYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string TrueValue {
            get {
                return ResourceManager.GetString("TrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to published.
        /// </summary>
        public static string VideoPublished {
            get {
                return ResourceManager.GetString("VideoPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string VideoTitle {
            get {
                return ResourceManager.GetString("VideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated.
        /// </summary>
        public static string VideoUpdated {
            get {
                return ResourceManager.GetString("VideoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        public static string VideoUrl {
            get {
                return ResourceManager.GetString("VideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web_info.
        /// </summary>
        public static string WebInfo {
            get {
                return ResourceManager.GetString("WebInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image_mega.
        /// </summary>
        public static string WebInfoImageExtraLarge {
            get {
                return ResourceManager.GetString("WebInfoImageExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image_large.
        /// </summary>
        public static string WebInfoImageLarge {
            get {
                return ResourceManager.GetString("WebInfoImageLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image_medium.
        /// </summary>
        public static string WebInfoImageMedium {
            get {
                return ResourceManager.GetString("WebInfoImageMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image_small.
        /// </summary>
        public static string WebInfoImageSmall {
            get {
                return ResourceManager.GetString("WebInfoImageSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to similar_artist.
        /// </summary>
        public static string WebInfoSimilarArtist {
            get {
                return ResourceManager.GetString("WebInfoSimilarArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        public static string WebInfoSimilarArtistImage {
            get {
                return ResourceManager.GetString("WebInfoSimilarArtistImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string WebInfoSimilarArtistName {
            get {
                return ResourceManager.GetString("WebInfoSimilarArtistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to similar_artists.
        /// </summary>
        public static string WebInfoSimilarArtists {
            get {
                return ResourceManager.GetString("WebInfoSimilarArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        public static string WebInfoSimilarArtistUrl {
            get {
                return ResourceManager.GetString("WebInfoSimilarArtistUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated.
        /// </summary>
        public static string WebInfoUpdated {
            get {
                return ResourceManager.GetString("WebInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wiki.
        /// </summary>
        public static string WebInfoWiki {
            get {
                return ResourceManager.GetString("WebInfoWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wikipedia.
        /// </summary>
        public static string Wikipedia {
            get {
                return ResourceManager.GetString("Wikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube.
        /// </summary>
        public static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
    }
}
