namespace Whip.Common
{
    public enum IconType
    {
        Archive,
        Book,
        Cog,
        Edit,
        ExclamationTriangle,
        Headphones,
        Home,
        Hourglass2,
        InfoCircle,
        KeyboardOutline,
        LastFmSquare,
        ListOl,
        ListUl,
        LongArrowRight,
        Music,
        PaintBrush,
        QuestionCircle,
        Random,
        Rss,
        Search,
        TimesRectangle,
        Users,
        VolumeDown,
        VolumeOff,
        VolumeUp
    }
}