//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whip.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Whip.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Add New....
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm:ss.
        /// </summary>
        public static string ApplicationPublishedFormat {
            get {
                return ResourceManager.GetString("ApplicationPublishedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whip.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.bandcamp.com/.
        /// </summary>
        public static string BandCampUrl {
            get {
                return ResourceManager.GetString("BandCampUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.bandsintown.com/{0}.
        /// </summary>
        public static string BandsInTownUrl {
            get {
                return ResourceManager.GetString("BandsInTownUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentlyPlaying.
        /// </summary>
        public static string CurrentPlayingDirectoryName {
            get {
                return ResourceManager.GetString("CurrentPlayingDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lyrics requested could not be found.
        /// </summary>
        public static string EditTrackLyricsNotFoundText {
            get {
                return ResourceManager.GetString("EditTrackLyricsNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics Not Found.
        /// </summary>
        public static string EditTrackLyricsNotFoundTitle {
            get {
                return ResourceManager.GetString("EditTrackLyricsNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://facebook.com/{0}.
        /// </summary>
        public static string FacebookUrl {
            get {
                return ResourceManager.GetString("FacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Error.
        /// </summary>
        public static string ImageErrorTitle {
            get {
                return ResourceManager.GetString("ImageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image was not loaded due to an internet connection error.
        /// </summary>
        public static string ImageInternetErrorText {
            get {
                return ResourceManager.GetString("ImageInternetErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem connecting to Last.FM. No further attempts will be made until the application is next started. If scrobbling is turned on, scrobbles will be cached and scrobbled later..
        /// </summary>
        public static string LastFmOffErrorMessageDetails {
            get {
                return ResourceManager.GetString("LastFmOffErrorMessageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.last.fm/music/{0}.
        /// </summary>
        public static string LastFmUrl {
            get {
                return ResourceManager.GetString("LastFmUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whiplogs.
        /// </summary>
        public static string LogFileDirectory {
            get {
                return ResourceManager.GetString("LogFileDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:yyyy-MM-dd}.log.
        /// </summary>
        public static string LogFileNameFormat {
            get {
                return ResourceManager.GetString("LogFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be more than {1} characters.
        /// </summary>
        public static string MaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("MaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connectivity has failed. The application will keep trying to connect to the internet. If scrobbling is turned on, scrobbles will be cached and scrobbled later..
        /// </summary>
        public static string OfflineErrorMessageDetails {
            get {
                return ResourceManager.GetString("OfflineErrorMessageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}.
        /// </summary>
        public static string RangeErrorMessage {
            get {
                return ResourceManager.GetString("RangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd\/MM\/yyyy HH\:mm\:ss.
        /// </summary>
        public static string StandardDateFormat {
            get {
                return ResourceManager.GetString("StandardDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm\:ss.
        /// </summary>
        public static string StandardTimeSpanFormat {
            get {
                return ResourceManager.GetString("StandardTimeSpanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string TabTitleLibrary {
            get {
                return ResourceManager.GetString("TabTitleLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info.
        /// </summary>
        public static string TabTitleSystemInfo {
            get {
                return ResourceManager.GetString("TabTitleSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/hashtag/{0}.
        /// </summary>
        public static string TwitterHashTagUrlFormat {
            get {
                return ResourceManager.GetString("TwitterHashTagUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/{0}.
        /// </summary>
        public static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/{0}.
        /// </summary>
        public static string TwitterUserUrlFormat {
            get {
                return ResourceManager.GetString("TwitterUserUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes on this tab. Are you happy to cancel these changes?.
        /// </summary>
        public static string UnsavedChangesText {
            get {
                return ResourceManager.GetString("UnsavedChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/{0}.
        /// </summary>
        public static string WikipediaUrl {
            get {
                return ResourceManager.GetString("WikipediaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/user/{0}.
        /// </summary>
        public static string YouTubeUrl {
            get {
                return ResourceManager.GetString("YouTubeUrl", resourceCulture);
            }
        }
    }
}
